Repository scheduleonce/once-ui, pull requests merged in 2022-12, with the labels that each got.

#982 Focus on our shared components buttons - is staying on focus state even after the action is done.
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/button/_button-icon.scss
  ui/src/components/button/_button-theme.scss
Labels: size/S, approved

#983 Fixing keyboard-program-focused
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/button/button.scss
Labels: size/S, approved

#984 ONCEHUB-60478: Pushing Ticket ONCEHUB-60478 with release 7.0.19
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/button/_button-icon.scss
  ui/src/components/button/_button-theme.scss
  ui/src/components/button/button.scss
Labels: approved, size/M

#987 Merging staging-app2 in to master.
  CHANGELOG.md
  Dockerfile
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/button/_button-icon.scss
  ui/src/components/button/_button-theme.scss
  ui/src/components/button/button.scss
Labels: approved, size/L

#986 Vulnerability fixes
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved

#988 Updating to 16.19.0-alpine3.16 via automated script
  Dockerfile
Labels: size/XS, approved
