Repository scheduleonce/once-ui, pull requests merged in 2022-10, with the labels that each got.

#959 Updating to 16.17.1-alpine3.16 via automated script
  CHANGELOG.md
  Dockerfile
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved

#961 Hurricanes/reverting 7.0.14 beta
  ui/package.json
  ui/src/components/paginator/paginator.html
Labels: size/XS, approved

#963 Flowing to revert commits to staging-app2
  ui/package.json
  ui/src/components/paginator/paginator.html
Labels: size/XS, approved

#960 Merging staging-app2 in to master.
  CHANGELOG.md
  Dockerfile
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved

#964 Vulnerability fixed
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/XXL, approved
