Repository scheduleonce/once-ui, pull requests merged in 2022-11, with the labels that each got.

#966 Strickers/fix vulnerabtility
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/XXL, approved

#969 Merging staging-app2 in to master.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/XXL, approved

#973 Vulnerability fixes
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: approved, size/L

#975 Updating code owners
  OWNERS_ALIASES
Labels: size/XS, approved

#977 ONCEHUB-60478: fixing focus state of buttons
  ui/src/components/button/_button-theme.scss
Labels: size/S, approved

#978 Releasing Beta version 7.0.18-beta.0
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved

#976 Updating to 16.18.1-alpine3.16 via automated script
  CHANGELOG.md
  Dockerfile
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved
