Repository scheduleonce/once-ui, pull requests merged in 2022-05, with the labels that each got.

#912 [Team]ONCEHUB-46511: added the functionality for cancel and done button for the multiselect dropdown
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/search/index.ts
  ui/src/components/select/select-module.ts
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
  ui/src/components/select/select.scss
  ui/src/stories/select/select.stories.mdx
Labels: approved, size/L

#914 [Team] ONCEHUB-46511: returning sting[] from the saveSelectionChange
  ui/src/components/select/select.component.ts
Labels: size/XS, approved

#915 [Team] ONCEHUB-46511: new Beta version release
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved

#913 Merging staging-app2 in to master.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/datepicker/calendar-body.spec.ts
  ui/src/components/datepicker/calendar-header.spec.ts
  ui/src/components/datepicker/calendar.spec.ts
  ui/src/components/datepicker/month-view.spec.ts
  ui/src/components/datepicker/multi-year-view.spec.ts
  ui/src/components/datepicker/native-date-adapter.spec.ts
  ui/src/components/datepicker/year-view.spec.ts
  ui/src/components/icon/icon.spec.ts
  ui/src/components/input/input.spec.ts
  ui/src/components/paginator/paginator.spec.ts
  ui/src/components/progress-bar/progress-bar.spec.ts
  ui/src/components/progress-spinner/progress-spinner.spec.ts
  ui/src/components/radio/radio.spec.ts
  ui/src/components/select/select.component.spec.ts
  ui/src/components/slide-toggle/slide-toggle.spec.ts
  ui/src/components/sort/sort.spec.ts
  ui/src/components/table/table.spec.ts
Labels: size/XXL, approved

#916 [Team] ONCEHUB-46511: new beta version release 7.0.5-beta.2
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
Labels: size/S, approved

#917 ONCEHUB-54491 : Migrated nodejs images to dockeronce and update docker files via automated script
  Dockerfile
Labels: size/XS, approved

#918 [QA] ONCEHUB-46511: Once UI - Enhance drop down with new functionality (added cancel and done buttons for multiSelect by passing actionItems in oui-selecct)
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/search/index.ts
  ui/src/components/select/select-module.ts
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
  ui/src/components/select/select.scss
  ui/src/stories/select/select.stories.mdx
Labels: approved, size/L

#919 Merging staging-app2 in to master
  CHANGELOG.md
  Dockerfile
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/search/index.ts
  ui/src/components/select/select-module.ts
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
  ui/src/components/select/select.scss
  ui/src/stories/select/select.stories.mdx
Labels: approved, size/L, do-not-merge/hold
