Repository scheduleonce/once-ui, pull requests merged in 2022-08, with the labels that each got.

#945 @storybook/storybook-deployer upgraded
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: approved, size/M

#946 [Team]ONCEHUB-55340: placeholder UI changes in ONCEHUB-ui and releasing the new beta version
  .storybook/preview-head.html
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.scss
Labels: approved, size/M

#947 OUI tooltip is not working correctly on the OnceUI pop up
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tooltip/tooltip-animations.ts
Labels: size/S, approved

#948 [Team] ONCEHUB-56974 : updated the cdk-keyboard-focused css properties so that it will look same in all browsers
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/button/button.scss
Labels: size/S, approved

#949 [Team]ONCEHUB-55340: line-height changed to 22px for all input fields and releasing beta version
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/form-field/_form-field-theme.scss
Labels: size/S, approved

#950 [QA] ONCEHUB-56974: updated the cdk-keyboard-focused css properties so that it will look same in all browsers
  ui/src/components/button/button.scss
Labels: size/XS, approved

#951 [QA] ONCEHUB-55340: placeholder UI changes in ONCEHUB-ui
  .storybook/preview-head.html
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/datepicker/_datepicker-theme.scss
  ui/src/components/form-field/_form-field-theme.scss
  ui/src/components/select/select.scss
  ui/src/components/tooltip/tooltip-animations.ts
Labels: approved, size/M

#952 ONCEHUB-57078 removing github actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/devskim-analysis.yml
Labels: approved, size/L

#953 Merging staging-app2 in to master.
  .storybook/preview-head.html
  CHANGELOG.md
  Dockerfile
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/button/button.scss
  ui/src/components/datepicker/_datepicker-theme.scss
  ui/src/components/form-field/_form-field-theme.scss
  ui/src/components/select/select.scss
  ui/src/components/tooltip/tooltip-animations.ts
Labels: approved, size/L
