Repository scheduleonce/once-ui, pull requests merged in 2022-04, with the labels that each got.

#888 https://scheduleonce.atlassian.net/browse/ONCEHUB-52065
  .lighthouse/jenkins-x/release.yaml
  deploy.sh
  package-deploy/npm-login.js
Labels: approved, size/M

#889 merge qa to team
  .lighthouse/jenkins-x/release.yaml
  deploy.sh
  package-deploy/npm-login.js
Labels: approved, size/M

#890 changed version to 7.0.3-beta.1
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: approved, size/M

#885 Vulnerability fixes
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: approved, size/L

#892 Ultragroot/oncehub 52065
  .lighthouse/jenkins-x/triggers.yaml
Labels: size/XS, approved

#891 Fixed vulnerabilities for node forge and minimist and https://scheduleonce.atlassian.net/browse/ONCEHUB-52065 on master
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
  CHANGELOG.md
  README.md
  deploy.sh
  package-deploy/npm-login.js
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: approved, size/L

#895 https://scheduleonce.atlassian.net/browse/ONCEHUB-53279
  .lighthouse/jenkins-x/release.yaml
  deploy.sh
Labels: size/S, approved

#896 [QA] ONCEHUB-51264: removed devdependency of gulp
  gulpfile.js
  package-lock.json
  package.json
Labels: size/XXL, approved

#897 Technocrats/update qa branch
  .lighthouse/jenkins-x/release.yaml
  deploy.sh
Labels: size/S, approved

#898 [QA] ONCEHUB-51264: package version changes
  package-lock.json
  package.json
  ui/src/components/datepicker/calendar-body.spec.ts
  ui/src/components/datepicker/calendar-header.spec.ts
  ui/src/components/datepicker/calendar.spec.ts
  ui/src/components/datepicker/month-view.spec.ts
  ui/src/components/datepicker/multi-year-view.spec.ts
  ui/src/components/datepicker/native-date-adapter.spec.ts
  ui/src/components/datepicker/year-view.spec.ts
  ui/src/components/icon/icon.spec.ts
  ui/src/components/input/input.spec.ts
  ui/src/components/paginator/paginator.spec.ts
  ui/src/components/progress-bar/progress-bar.spec.ts
  ui/src/components/progress-spinner/progress-spinner.spec.ts
  ui/src/components/radio/radio.spec.ts
  ui/src/components/select/select.component.spec.ts
  ui/src/components/slide-toggle/slide-toggle.spec.ts
  ui/src/components/sort/sort.spec.ts
  ui/src/components/table/table.spec.ts
Labels: size/XXL, approved

#899 [QA] ONCEHUB-51264: updated karma-jasmine dev dependency from 4.0.0 to 5.0.0 also removed ncu which is wrongly added
  package-lock.json
  package.json
Labels: approved, size/XL

#900 [Team] ONCEHUB-51264: beta version release from 7.0.3 to 7.0.4-beta.0
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved

#901 [Team] ONCEHUB-51264: beta version release from 7.0.3 to 7.0.4-beta.2
  gulpfile.js
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/XXL, approved

#902 [Team]ONCEHUB-51264: Oncehub-ui beta version updated for the sanity
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved

#903 Revert "https://scheduleonce.atlassian.net/browse/ONCEHUB-53279"
  .lighthouse/jenkins-x/release.yaml
  deploy.sh
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved

#905 [QA] ONCEHUB-51264: gulp added and added 7.0.3 version of once-ui
  gulpfile.js
  package-lock.json
  package.json
Labels: size/XXL, approved

#906 [Team] technocrats/postbuild-issue: once-ui new beta version release
  .lighthouse/jenkins-x/release.yaml
  deploy.sh
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved

#908 testing with master code for gulp
  package.json
  ui/node_modules/.package-lock.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved

#909 [QA] ONCEHUB-51264: folder changes where the scss files exports
  gulpfile.js
Labels: size/XS, approved

#910 [Team] ONCEHUB-51264: folder changes where the scss files exports and new beta version release
  gulpfile.js
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved
