Repository scheduleonce/once-ui, pull requests merged in 2022-03, with the labels that each got.

#871 Ultragroot/oncehub 51572
  Jenkinsfile_NotUsed
Labels: size/L

#875 Rename Lighthouse folder name
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
Labels: size/XS

#879 add Kptfile manually
  .lighthouse/jenkins-x/Kptfile
Labels: size/S

#880 Ultragroot/oncehub 51572
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/M

#884 Update README.md
  README.md
Labels: size/XS, approved

#886 Vulnerability fixes
  package-lock.json
  package.json
Labels: approved, size/M
