Repository scheduleonce/once-ui, pull requests merged in 2022-07, with the labels that each got.

#926 add month name in calendar header and remove month name from month view
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/datepicker/calendar-body.html
  ui/src/components/datepicker/calendar.ts
Labels: approved, size/M

#929 Fixing package publish issue
  .gitignore
  ui/package-lock.json
  ui/package.json
Labels: size/XS, approved

#932 Merging staging-app2 in to master.
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/datepicker/calendar-body.html
  ui/src/components/datepicker/calendar.ts
Labels: approved, size/M

#934 ONCEHUB-49478 adding merge status to staging-app2
  .lighthouse/jenkins-x/pullrequest.yaml
Labels: approved, size/M

#939 Remove duplicate checks
  .lighthouse/jenkins-x/pullrequest.yaml
Labels: size/S, approved

#937 Terser vulnerability fixed
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: approved, size/L

#940 [Team] technocrats/node-alpine-update: releasing the beta version for node and alpine update
  .lighthouse/jenkins-x/pullrequest.yaml
  CHANGELOG.md
  Dockerfile
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: approved, size/L

#943 Remove Multiple checks
  .lighthouse/jenkins-x/pullrequest.yaml
Labels: size/S, approved

#941 Merging staging-app2 in to master.
  .gitignore
  .lighthouse/jenkins-x/pullrequest.yaml
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: approved, size/M

#944 Updating to 16.16.0-alpine3.16 via automated script
  CHANGELOG.md
  Dockerfile
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved
