Repository scheduleonce/once-ui, pull requests merged in 2023-01, with the labels that each got.

#989 Vulnerability fixes
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: approved, size/L

#990 Merging staging-app2 in to master.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved

#979 Upgrading the angular version to 14
  .lighthouse/jenkins-x/pullrequest.yaml
  CHANGELOG.md
  angular.json
  documentation.json
  package-lock.json
  package.json
  tsconfig.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/autocomplete/autocomplete.spec.ts
  ui/src/components/autocomplete/autocomplete.ts
  ui/src/components/checkbox/checkbox.spec.ts
  ui/src/components/checkbox/checkbox.ts
  ui/src/components/core/common-behaviors/error-options.ts
  ui/src/components/core/common-behaviors/error-state.ts
  ui/src/components/core/error/error-options.ts
  ui/src/components/datepicker/calendar-body.ts
  ui/src/components/datepicker/datepicker-module.ts
  ui/src/components/datepicker/datepicker.spec.ts
  ui/src/components/datepicker/month-view.ts
  ui/src/components/dialog/dialog-module.ts
  ui/src/components/input/input.spec.ts
  ui/src/components/radio/radio.spec.ts
  ui/src/components/radio/radio.ts
  ui/src/components/select/select.component.spec.ts
  ui/src/components/select/select.component.ts
  ui/src/components/tooltip/tooltip-module.ts
  ui/src/stories/autocomplete/autocomplete.component.ts
  ui/tsconfig.lib.json
Labels: size/XXL, approved

#994 ONCEHUB-62122: multi select checkbox fix
  ui/src/components/core/selection/pseudo-checkbox/pseudo-checkbox.scss
Labels: size/XS, approved, do-not-merge/hold

#995 updating once-ui version to 7.0.22-beta.1
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved

#996 Merging staging-app2 in to master.
  CHANGELOG.md
  Dockerfile
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: approved, size/L

#997 Updating to 18.13.0-alpine3.17 via automated script
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile
Labels: size/XS, approved
