Repository scheduleonce/once-ui, pull requests merged in 2023-08, with the labels that each got.

#1065 Updating to 18.17.0-alpine3.18 via automated script
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile
Labels: size/XS, approved

#1066 Merging staging-app2 in to master.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: approved, size/L

#1062 ONCEHUB-65303 Upgraded angular to v16
  .storybook/main.js
  CHANGELOG.md
  angular.json
  documentation.json
  migration-storybook.log
  package-lock.json
  package.json
  tsconfig.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/datepicker/date-adapter.ts
  ui/src/components/dialog/dialog-scroll-strategy.ts
  ui/src/components/index.ts
  ui/src/test.ts
  ui/tsconfig.lib.json
Labels: size/XXL, approved

#1067 ONCEHUB-65303 Upgraded angular to v16
  .lighthouse/jenkins-x/release.yaml
Labels: size/XS, approved

#1068 added scrollbar
  ui/src/components/scrollbar/public-api.ts
Labels: size/XS, approved

#1069 Merging staging-app2 in to master.
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile
Labels: size/XS, approved

#1070 [Team] ONCEHUB-62187: added the accessibility for the actionItems in multiSelect dropdown
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
Labels: approved, size/M
