Repository scheduleonce/once-ui, pull requests merged in 2023-10, with the labels that each got.

#1079 Spacing issue on oui-scrollbar when scrollbar is not visible
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/scrollbar/scrollbar.scss
Labels: size/S, approved

#1081 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: size/XS, approved

#1082 Spacing issue on oui-scrollbar when scrollbar is not visible
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/scrollbar/scrollbar.scss
Labels: size/S, approved

#1084 [Team] accessibility-revert : reverting accessibility changes
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
Labels: approved, size/L

#1086 Revert "[Team] accessibility-revert : reverting accessibility changes"
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
Labels: approved, size/L

#1085 [Team]ONCEHUB-73533: in search space key was not working properly now fixed
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
Labels: approved, size/M

#1087 [QA] ONCEHUB-73533: in search space key was not working properly now fixed also releasing the latest version of once-ui
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
Labels: approved, size/M

#1088 Merging staging-app2 in to master.
  .lighthouse/jenkins-x/release.yaml
  .storybook/main.js
  CHANGELOG.md
  OWNERS_ALIASES
  angular.json
  documentation.json
  migration-storybook.log
  package-lock.json
  package.json
  tsconfig.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/datepicker/date-adapter.ts
  ui/src/components/dialog/dialog-scroll-strategy.ts
  ui/src/components/index.ts
  ui/src/components/scrollbar/public-api.ts
  ui/src/components/scrollbar/scrollbar.scss
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
  ui/src/test.ts
  ui/tsconfig.lib.json
Labels: size/XXL, approved

#1092 Updating to 18.18.2-alpine3.18 via automated script
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile
Labels: size/XS, approved
