Repository scheduleonce/once-ui, pull requests merged in 2023-05, with the labels that each got.

#1041 Merging staging-app2 in to master.
  package-lock.json
Labels: size/XXL, approved

#1044 Vulnerability fixes
  package-lock.json
Labels: size/S, approved

#1045 update version after vulnerability fix
  CHANGELOG.md
  package.json
Labels: size/XS, approved

#1048 version upgrade
  ui/package-lock.json
  ui/package.json
Labels: size/XS, approved
