Repository scheduleonce/once-ui, pull requests merged in 2023-11, with the labels that each got.

#1093 Merging staging-app2 in to master.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
Labels: approved, size/M

#1094 pushed new version for once ui to resolve vulnerability
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: approved, size/L

#1095 Merging staging-app2 in to master.
  .lighthouse/jenkins-x/pullrequest.yaml
  CHANGELOG.md
  Dockerfile
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/XXL, approved
