Repository scheduleonce/once-ui, pull requests merged in 2023-09, with the labels that each got.

#1071 kaniko image upgrade
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/XS, approved

#1073 removed vulnerability @adobe/css-tools
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S

#1074 [Team] ONCEHUB-62187: included searchbar in the accessibility flow
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
Labels: approved, size/M

#1075 ONCEHUB-65303 Upgade Angular to v16
  .lighthouse/jenkins-x/release.yaml
  .storybook/main.js
  CHANGELOG.md
  angular.json
  documentation.json
  migration-storybook.log
  package-lock.json
  package.json
  tsconfig.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/datepicker/date-adapter.ts
  ui/src/components/dialog/dialog-scroll-strategy.ts
  ui/src/components/index.ts
  ui/src/components/scrollbar/public-api.ts
  ui/src/test.ts
  ui/tsconfig.lib.json
Labels: size/XXL, approved

#1077 [Team] ONCEHUB-62187: included searchbar in the accessibility flow
  .lighthouse/jenkins-x/release.yaml
  .storybook/main.js
  CHANGELOG.md
  angular.json
  documentation.json
  migration-storybook.log
  package-lock.json
  package.json
  tsconfig.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/datepicker/date-adapter.ts
  ui/src/components/dialog/dialog-scroll-strategy.ts
  ui/src/components/index.ts
  ui/src/components/scrollbar/public-api.ts
  ui/src/components/select/select.component.ts
  ui/src/test.ts
  ui/tsconfig.lib.json
Labels: size/XXL, approved
