Repository scheduleonce/once-ui, pull requests merged in 2023-12, with the labels that each got.

#1096 [ONCEHUB-74291] [Prod] Defects on scroll UX/UI on left nav
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/scrollbar/scrollbar.scss
Labels: size/S, approved

#1097 [ONCEHUB-74291] [Prod] Defects on scroll UX/UI on left nav
  CHANGELOG.md
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/scrollbar/scrollbar.scss
Labels: size/S, approved

#1098 Pythons/oncehub 73711
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/scrollbar/scrollbar.scss
  ui/src/components/select/search/option-search.scss
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
  ui/src/components/select/select.scss
Labels: approved, size/M

#1100 version correction
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved

#1101 version upgrade
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved

#1102 Pythons/oncehub 73711
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/search/option-search.scss
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
  ui/src/components/select/select.scss
Labels: approved, size/M

#1104 [ONCEHUB-75540] [Prod] Getting console error on adding users
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/panel/panel-trigger.ts
Labels: size/XXL, approved

#1105 QA to Master
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/scrollbar/scrollbar.scss
  ui/src/components/select/search/option-search.scss
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
  ui/src/components/select/select.scss
Labels: approved, size/M

#1106 [ONCEHUB-75540] [Prod] Getting console error on adding users
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/panel/panel-trigger.ts
Labels: size/XXL, approved

#1110 Fix UI issue for select checkbox
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/core/selection/pseudo-checkbox/pseudo-checkbox.scss
Labels: approved, size/M

#1113 fix UI issue for checkbox in oui-multiselect
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/core/selection/pseudo-checkbox/pseudo-checkbox.scss
Labels: size/S, approved

#1114 fix checkbox UI in multi selectbox
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/core/selection/pseudo-checkbox/pseudo-checkbox.scss
Labels: approved, size/M

#1115 Pythons/oncehub 73711
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/core/selection/pseudo-checkbox/pseudo-checkbox.scss
Labels: approved, size/M

#1117 added css for focused and hover state
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tabs/_tabs-common.scss
Labels: size/S, approved
