Repository scheduleonce/once-ui, pull requests merged in 2023-06, with the labels that each got.

#1051 ONCE-UI Angular version upgrade from v14 to v15
  CHANGELOG.md
  documentation.json
  package-lock.json
  package.json
  tsconfig.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/datepicker/date-adapter.ts
  ui/src/components/dialog/dialog-scroll-strategy.ts
  ui/src/test.ts
  ui/tsconfig.lib.json
Labels: size/XXL, approved

#1052 updated node version from 16 to 18.16.0 #118
  .lighthouse/jenkins-x/release.yaml
Labels: size/XS, approved

#1053 Merging staging-app2 in to master.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved
