Repository scheduleonce/once-ui, pull requests merged in 2023-03, with the labels that each got.

#1019 [ONCEHUB-63483] - [App2] [Licenses] : When the user name is entered in the search text field entered username is not able to select the checkbox for the second click of the enter button.
  deploy.sh
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/stories/button/button.stories.mdx
Labels: size/S, approved

#1023 Merging staging-app2 in to master.
  CHANGELOG.md
  Dockerfile
  deploy.sh
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/core/selection/pseudo-checkbox/pseudo-checkbox.scss
Labels: approved, size/M

#1022 ONCEHUB-60511 Upgrade angular version to 14.x
  .lighthouse/jenkins-x/pullrequest.yaml
  CHANGELOG.md
  angular.json
  documentation.json
  package-lock.json
  package.json
  tsconfig.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/autocomplete/autocomplete.spec.ts
  ui/src/components/autocomplete/autocomplete.ts
  ui/src/components/checkbox/checkbox.spec.ts
  ui/src/components/checkbox/checkbox.ts
  ui/src/components/core/common-behaviors/error-options.ts
  ui/src/components/core/common-behaviors/error-state.ts
  ui/src/components/core/error/error-options.ts
  ui/src/components/datepicker/calendar-body.ts
  ui/src/components/datepicker/datepicker-module.ts
  ui/src/components/datepicker/datepicker.spec.ts
  ui/src/components/datepicker/month-view.ts
  ui/src/components/dialog/dialog-module.ts
  ui/src/components/input/input.spec.ts
  ui/src/components/radio/radio.spec.ts
  ui/src/components/radio/radio.ts
  ui/src/components/select/select.component.spec.ts
  ui/src/components/select/select.component.ts
  ui/src/components/tooltip/tooltip-module.ts
  ui/src/stories/autocomplete/autocomplete.component.ts
  ui/tsconfig.lib.json
Labels: size/XXL, approved

#1025 [ONCEHUB-63483] - [App2] [Licenses] : When the user name is entered in the search text field entered username is not able to select the checkbox for the second click of the enter button
  .lighthouse/jenkins-x/pullrequest.yaml
  CHANGELOG.md
  angular.json
  documentation.json
  package-lock.json
  package.json
  tsconfig.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/autocomplete/autocomplete.spec.ts
  ui/src/components/autocomplete/autocomplete.ts
  ui/src/components/checkbox/checkbox.spec.ts
  ui/src/components/checkbox/checkbox.ts
  ui/src/components/core/common-behaviors/error-options.ts
  ui/src/components/core/common-behaviors/error-state.ts
  ui/src/components/core/error/error-options.ts
  ui/src/components/datepicker/calendar-body.ts
  ui/src/components/datepicker/datepicker-module.ts
  ui/src/components/datepicker/datepicker.spec.ts
  ui/src/components/datepicker/month-view.ts
  ui/src/components/dialog/dialog-module.ts
  ui/src/components/input/input.spec.ts
  ui/src/components/radio/radio.spec.ts
  ui/src/components/radio/radio.ts
  ui/src/components/select/select.component.spec.ts
  ui/src/components/select/select.component.ts
  ui/src/components/tooltip/tooltip-module.ts
  ui/src/stories/autocomplete/autocomplete.component.ts
  ui/tsconfig.lib.json
Labels: size/XXL, approved

#1026 [ONCEHUB-63483] - [App2] [Licenses] : When the user name is entered in the search text field entered username is not able to select the checkbox for the second click of the enter button
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/search/index.ts
  ui/src/components/select/search/option-search.html
  ui/src/components/select/select.component.ts
  ui/src/stories/button/button.stories.mdx
Labels: size/XXL, approved

#1030 [ONCEHUB-65725] [app3] Interactions are getting auto populated when we create bot/form from scratch or template and save button is getting enabled in a scenario.
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
Labels: approved, size/M

#1031 https://scheduleonce.atlassian.net/browse/ONCEHUB-65796 - Optimize CPU resources for JenkinsX PR & Release checks
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/XS

#1032 [ONCEHUB-65725] [app3] Interactions are getting auto populated when we create bot/form from scratch or template and save button is getting enabled in a scenario.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
Labels: approved, size/M

#1033 Merging staging-app2 in to master.
  .lighthouse/jenkins-x/pullrequest.yaml
  CHANGELOG.md
  angular.json
  documentation.json
  package-lock.json
  package.json
  tsconfig.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/autocomplete/autocomplete.spec.ts
  ui/src/components/autocomplete/autocomplete.ts
  ui/src/components/checkbox/checkbox.spec.ts
  ui/src/components/checkbox/checkbox.ts
  ui/src/components/core/common-behaviors/error-options.ts
  ui/src/components/core/common-behaviors/error-state.ts
  ui/src/components/core/error/error-options.ts
  ui/src/components/datepicker/calendar-body.ts
  ui/src/components/datepicker/datepicker-module.ts
  ui/src/components/datepicker/datepicker.spec.ts
  ui/src/components/datepicker/month-view.ts
  ui/src/components/dialog/dialog-module.ts
  ui/src/components/input/input.spec.ts
  ui/src/components/radio/radio.spec.ts
  ui/src/components/radio/radio.ts
  ui/src/components/select/select.component.spec.ts
  ui/src/components/select/select.component.ts
  ui/src/components/tooltip/tooltip-module.ts
  ui/src/stories/autocomplete/autocomplete.component.ts
  ui/tsconfig.lib.json
Labels: size/XXL, approved

#1027 Updating to 18.13.0-alpine3.17 via automated script
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile
  package-lock.json
Labels: approved, size/M
