Repository scheduleonce/once-ui, pull requests merged in 2023-07, with the labels that each got.

#1056 Vulnerability fixes
  package-lock.json
Labels: size/XXL, approved

#1057 Merging staging-app2 in to master.
  package-lock.json
Labels: size/XXL, approved

#1058 Vulnerability fixes
  package-lock.json
Labels: size/L

#1059 Changed version of package after vulnerability fixes
  package.json
Labels: size/XS

#1060 Update package.json after vulnerability fix
  CHANGELOG.md
  package-lock.json
  ui/package-lock.json
  ui/package.json
Labels: size/S
