Repository scheduleonce/once-ui, pull requests merged in 2023-02, with the labels that each got.

#1002 [ONCEHUB-63483] - [App2] [Licenses] : When the user name is entered in the search text field entered username is not able to select the checkbox for the second click of the enter button.
  Dockerfile
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/search/index.ts
  ui/src/components/select/search/option-search.html
  ui/src/components/select/select.component.ts
Labels: size/M

#1005 Add logging of npm and node version to debug failing PR checks
  Dockerfile
  deploy.sh
Labels: size/XS, approved

#1003 Updating to 16.19.0-alpine3.16 via automated script
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile
Labels: size/XS, approved

#1004 Merging staging-app2 in to master.
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile
Labels: size/XS, approved

#1010 Fixed PR checks
  .lighthouse/jenkins-x/pullrequest.yaml
Labels: size/XS, approved

#999 ONCEHUB-62122: Fix multi select checkbox same as oui-checkbox
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/core/selection/pseudo-checkbox/pseudo-checkbox.scss
Labels: approved

#1012 Update release.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/XS, approved

#1013 Ultragroot/oncehub 64838 1
  .lighthouse/jenkins-x/release.yaml
  Dockerfile
Labels: size/XS

#1014 Fixed Checks
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile
Labels: size/XS, approved

#1011 Merging staging-app2 in to master.
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile
Labels: size/S, approved

#1015 Update release.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/XS, approved

#1016 Update deploy.sh
  deploy.sh
Labels: size/XS

#1018 Vulnerability fixes
  package-lock.json
Labels: size/S, approved
