Repository scheduleonce/once-ui, pull requests merged in 2024-06, with the labels that each got.

#1192 update the outline with box-shadow to resolve issue in safari
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/button/button.scss
Labels: size/S, approved

#1193 Fix: Text links have rounded corner focus states in Safari browser - ONCEHUB-25174
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/button/button.scss
  ui/src/components/button/button.ts
Labels: size/S, approved

#1194 Merging staging-app2 in to master.
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
  ui/src/stories/select/select.stories.mdx
Labels: approved, size/M

#1197 fix scrolling issue for multiline option in select
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/core/option/option.ts
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
Labels: approved, size/M

#1199 fix scroll for searchbox schenario
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
Labels: size/S, approved

#1200 added oui-align-tabs with 'start, center, end'
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tabs/_tabs-common.scss
  ui/src/stories/tabs/tabs.component.ts
Labels: size/S, approved

#1201 Updating to 20.14.0-alpine3.20 via automated script
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile
Labels: size/XS, approved

#1203 update the oui-tab with dynamic values
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tabs/tab-body.ts
  ui/src/components/tabs/tab-group.ts
  ui/src/components/tabs/tab-nav-bar/tab-nav-bar.scss
  ui/src/components/tabs/tab.ts
Labels: approved, size/M

#1205 fix test case issue for null check
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
Labels: size/S, approved

#1204 Updating to 20.14.0-alpine3.20 via automated script
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile
Labels: size/XS, approved

#1206 fix test case issue for null check
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
Labels: size/S, approved

#1207 update the oui-tab with dynamic values after first load
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tabs/tab-body.ts
  ui/src/components/tabs/tab.ts
Labels: approved, size/M

#1210 Ref: Implemented `_toggleFocus` method to dynamically add or remove focus from the dialog container
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/dialog/dialog-container.ts
Labels: size/S, approved

#1211 added oui-align-tabs with 'start, center, end'
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tabs/_tabs-common.scss
  ui/src/components/tabs/tab-body.ts
  ui/src/components/tabs/tab-group.ts
  ui/src/components/tabs/tab-nav-bar/tab-nav-bar.scss
  ui/src/components/tabs/tab.ts
  ui/src/stories/tabs/tabs.component.ts
  ui/src/stories/tabs/tabs.stories.mdx
Labels: approved, size/L

#1212 Fixing the checkbox UI and scrolling issue for accessing option via keyboard's arrow keys.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/core/option/option.ts
  ui/src/components/core/selection/pseudo-checkbox/pseudo-checkbox.scss
  ui/src/components/select/search/index.ts
  ui/src/components/select/search/option-search.scss
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
  ui/src/components/select/select.scss
Labels: approved, size/L

#1213 Merging staging-app2 in to master.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/button/button.scss
  ui/src/components/button/button.ts
Labels: size/S, approved

#1214 updated the change log
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: approved, size/XL

#1216 Implemented toggleFocus method to dynamically add or remove focus from the dialog container based on a boolean parameter
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/dialog/dialog-container.ts
  ui/src/components/dialog/dialog-ref.ts
Labels: approved, size/M

#1218 [Team]ONCEHUB-83190: added new singleActionItem for all type of dd
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
  ui/src/components/select/select.scss
  ui/src/stories/select/select.stories.mdx
Labels: approved, size/M

#1219 Avengers/vulnerability fix ws socket
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: approved, size/XL
