Repository scheduleonce/once-ui, pull requests merged in 2024-07, with the labels that each got.

#1220 Adding console log in ouitooltip
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tooltip/tooltip.ts
Labels: size/S, approved

#1221 [Team]ONCEHUB-83190: Added a new single select actionItem with accessibility to focus dropdown button and searchfields also released a beta version
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
  ui/src/components/select/select.scss
  ui/src/stories/select/select.stories.mdx
Labels: approved, size/L

#1222 [ONCE-UI] Done gets enable while there were no changes in the dropdown
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
Labels: approved, size/M

#1223 fix: Occasionally, when hovering over elements that contain ouiToolTi…
  CHANGELOG.md
  package.json
  ui/src/components/tooltip/tooltip.html
Labels: approved

#1224 prettier fix
  CHANGELOG.md
Labels: size/XS, approved

#1225 change version
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved

#1226 https://scheduleonce.atlassian.net/browse/ONCEHUB-83691 update: packa…
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/dialog/dialog-content.ts
  ui/src/components/dialog/dialog.scss
  ui/src/stories/icon/icon.component.ts
Labels: size/S, approved

#1227 fix style issue
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tooltip/tooltip.html
Labels: size/S, approved

#1229 dispose overlay on tooltip hide
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tooltip/tooltip.html
  ui/src/components/tooltip/tooltip.ts
Labels: approved, size/M

#1230 [ONCE-UI] Done gets enable while there were no changes in the dropdown
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
Labels: approved, size/M

#1232 Merging staging-app2 in to master.
  .lighthouse/jenkins-x/pullrequest.yaml
  CHANGELOG.md
  Dockerfile
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/core/option/option.ts
  ui/src/components/core/selection/pseudo-checkbox/pseudo-checkbox.scss
  ui/src/components/dialog/dialog-container.ts
  ui/src/components/dialog/dialog-ref.ts
  ui/src/components/select/search/index.ts
  ui/src/components/select/search/option-search.scss
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
  ui/src/components/select/select.scss
  ui/src/components/tabs/_tabs-common.scss
  ui/src/components/tabs/tab-body.ts
  ui/src/components/tabs/tab-group.ts
  ui/src/components/tabs/tab-nav-bar/tab-nav-bar.scss
  ui/src/components/tabs/tab.ts
  ui/src/stories/tabs/tabs.component.ts
  ui/src/stories/tabs/tabs.stories.mdx
Labels: size/XXL, approved

#1233 Update the color of icona nd hover effect https://scheduleonce.atlass…
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/dialog/dialog.scss
Labels: size/S, approved

#1234 fix: Occasionally, when hovering over elements that contain ouiToolTi…
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tooltip/tooltip.ts
Labels: size/S, approved

#1235 Fix: [PROD] Tabs ui design-shared oui component- fix the color of the not selected - ONCEHUB-84773
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tabs/_tabs-common.scss
Labels: approved

#1237 Fix: [PROD] Tabs ui design-shared oui component- fix the color of the not selected - ONCEHUB-84773
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tabs/tab-nav-bar/tab-nav-bar.scss
Labels: size/S, approved

#1236 [Team] ONCEHUB-83190: removed the text-decoration on hover and focus from singleActionItem
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.scss
Labels: approved

#1238 Fix: [PROD] Tabs ui design-shared oui component- fix the text color of the not selected - ONCEHUB-84773
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tabs/_tabs-common.scss
  ui/src/components/tabs/tab-nav-bar/tab-link.scss
  ui/src/components/tabs/tab-nav-bar/tab-nav-bar.scss
Labels: size/S, approved

#1239 Fix: [PROD] Tabs ui design-shared oui component- fix the text color of the not selected - ONCEHUB-84773
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tabs/tab-nav-bar/tab-link.scss
Labels: size/S, approved

#1240 [QA] ONCEHUB-83190: Create singleActionItem bar for singleSelect and multiSelect.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
  ui/src/components/select/select.scss
  ui/src/stories/select/select.stories.mdx
Labels: approved, size/L

#1241 Fixed the tabs stretch UI
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tabs/tab-nav-bar/tab-nav-bar.scss
Labels: size/S, approved

#1242 Merging staging-app2 in to master.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/dialog/dialog-content.ts
  ui/src/components/dialog/dialog.scss
  ui/src/components/tabs/tab-nav-bar/tab-link.scss
  ui/src/components/tooltip/tooltip.ts
  ui/src/stories/icon/icon.component.ts
Labels: approved, size/M
