Repository scheduleonce/once-ui, pull requests merged in 2024-03, with the labels that each got.

#1148 [fixed] vulnerability found in package es5-ext [APP3 PR 2]
  ui/package-lock.json
  ui/package.json
Labels: size/XS, approved

#1149 [once-ui] Change the attribute text to ng-content in oui-tabs
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tabs/tab-group.html
  ui/src/components/tabs/tab-group.ts
  ui/src/components/tabs/tab.html
  ui/src/components/tabs/tab.ts
  ui/src/stories/tabs/tabs.component.ts
Labels: size/S, approved

#1150 update the stretch tabs css
  ui/src/components/tabs/_tabs-common.scss
  ui/src/stories/tabs/tabs.component.ts
Labels: size/S, approved

#1151 update version to 8.0.14-beta.1
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved

#1153 Fixed the issue for the nav bar link
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tabs/_tabs-common.scss
  ui/src/components/tabs/_tabs-theme.scss
  ui/src/components/tabs/tab-group.ts
  ui/src/components/tabs/tab-nav-bar/tab-link.scss
  ui/src/components/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: approved, size/L

#1154 fixed the focus state and some css
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tabs/_tabs-theme.scss
  ui/src/components/tabs/tab-nav-bar/tab-link.scss
  ui/src/components/tabs/tab-nav-bar/tab-nav-bar.scss
  ui/src/stories/tabs/tabs.component.ts
Labels: approved, size/M

#1155 [once-ui] Change the attribute text to ng-content in oui-tabs
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tabs/_tabs-common.scss
  ui/src/components/tabs/_tabs-theme.scss
  ui/src/components/tabs/tab-group.html
  ui/src/components/tabs/tab-group.ts
  ui/src/components/tabs/tab-nav-bar/tab-link.scss
  ui/src/components/tabs/tab-nav-bar/tab-nav-bar.scss
  ui/src/components/tabs/tab-nav-bar/tab-nav-bar.ts
  ui/src/components/tabs/tab.html
  ui/src/components/tabs/tab.ts
  ui/src/stories/tabs/tabs.component.ts
Labels: approved, size/L

#1156 Merging staging-app2 in to master.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: approved, size/M

#1158 fix checkbox UI in multi select box and fix scroll issue
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/core/selection/pseudo-checkbox/pseudo-checkbox.scss
  ui/src/components/select/search/index.ts
  ui/src/components/select/search/option-search.scss
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
  ui/src/components/select/select.scss
Labels: approved, size/L
