Repository scheduleonce/once-ui, pull requests merged in 2024-09, with the labels that each got.

#1259 Merging staging-app2 in to master.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: approved

#1260 Updating to 20.17.0-alpine3.20 via automated script
  Dockerfile
Labels: approved

#1261 Updating to angular-v20.17.0 via automated script
  .lighthouse/jenkins-x/pullrequest.yaml
Labels: size/XS, approved

#1263 Fix: ONCEHUB-87445: Update storybook in once-ui to version 8.x
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved
