Repository scheduleonce/once-ui, pull requests merged in 2024-11, with the labels that each got.

#1280 Update npm packages
  package-lock.json
Labels: size/XS, approved

#1282 The arrows in input type number should be same in all browsers - ONCEHUB-89881
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/form-field/_form-field-theme.scss
  ui/src/components/input/input-module.ts
  ui/src/components/input/input.ts
Labels: approved, size/M

#1283 The arrows in input type number should be same in all browsers - ONCEHUB-89881
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/input/input.ts
Labels: approved, size/M

#1285 Merging staging-app2 in to master.
  package-lock.json
Labels: approved

#1289 Update npm packages
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile
Labels: size/S, approved
