Repository scheduleonce/once-ui, pull requests merged in 2024-04, with the labels that each got.

#1161 testing changes
  .lighthouse/jenkins-x/release.yaml
  deploy.sh
  package-deploy/azure-login.js
  package-lock.json
  package.json
Labels: approved, size/M

#1162 testing changes
  deploy.sh
Labels: size/XS, approved

#1163 testing changes for pushing to npm & azure
  .lighthouse/jenkins-x/release.yaml
  deploy-azure.sh
  deploy-npm.sh
Labels: approved, size/M

#1164 test
  .lighthouse/jenkins-x/release.yaml
  package-lock.json
  package.json
Labels: size/S, approved

#1165 test
  .lighthouse/jenkins-x/release.yaml
Labels: size/S, approved

#1166 test
  ui/package-lock.json
  ui/package.json
Labels: size/XS, approved

#1167 test
  deploy-azure.sh
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved

#1168 Merging staging-app2 in to master.
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tabs/_tabs-common.scss
  ui/src/components/tabs/_tabs-theme.scss
  ui/src/components/tabs/tab-group.html
  ui/src/components/tabs/tab-group.ts
  ui/src/components/tabs/tab-nav-bar/tab-link.scss
  ui/src/components/tabs/tab-nav-bar/tab-nav-bar.scss
  ui/src/components/tabs/tab-nav-bar/tab-nav-bar.ts
  ui/src/components/tabs/tab.html
  ui/src/components/tabs/tab.ts
  ui/src/stories/tabs/tabs.component.ts
Labels: approved, size/L

#1172 added a method in ouiDialog service to remove or add focus in dialog
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/dialog/dialog-container.ts
  ui/src/components/dialog/dialog.ts
Labels: approved, size/M

#1174 Updating to 18.20.2-alpine3.19 via automated script
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile
Labels: size/XS, approved

#1177 Avengers/tar 6.1.15 6.2.1
  package-lock.json
Labels: size/S, approved
