Repository scheduleonce/once-ui, pull requests merged in 2024-02, with the labels that each got.

#1132 [fixed] vulnerability found in package vite [APP3 PR]
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S

#1134 Fixed, on searching the option the focus should scroll to the focused potion.
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/core/option/option.ts
Labels: size/S, approved

#1135 oui-scrollbar look is broken in Chrome 121
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/scrollbar/scrollbar.scss
Labels: approved, size/M

#1136 Merging staging-app2 in to master.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tabs/_tabs-common.scss
Labels: size/S, approved

#1137 oui-scrollbar look is broken in Chrome 121
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/scrollbar/scrollbar.scss
Labels: approved, size/M

#1138 Fixed, on searching the option the focus should scroll to the focused potion.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/core/option/option.ts
Labels: size/S, approved

#1139 Change "d1azc1qln24ryf.cloudfront.net" to "cdn.icomoon.io"
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/stories/button/button.component.ts
  ui/src/stories/button/button.stories.mdx
  ui/src/stories/icon/icon.component.ts
  ui/src/stories/menu/menu.component.ts
  ui/src/stories/tooltip/tooltip.component.ts
Labels: approved, size/M

#1142 Vulnerability fixes
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved
