Repository scheduleonce/once-ui, pull requests merged in 2024-08, with the labels that each got.

#1243 replaced the ip package with ip-address to fix the vulnerability
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/XXL, approved

#1244 Merging staging-app2 in to master.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
  ui/src/components/select/select.scss
  ui/src/components/tabs/tab-nav-bar/tab-nav-bar.scss
  ui/src/stories/select/select.stories.mdx
Labels: approved, size/L

#1246 updated package lock json
  package-lock.json
Labels: size/XS, approved

#1248 chore: Update Node.js image version to angular-v20.14.0 for Jenkins-X release.yaml file
  .lighthouse/jenkins-x/release.yaml
Labels: size/XS, approved

#1249 Merging staging-app2 in to master.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/XXL, approved
