Repository scheduleonce/once-ui, pull requests merged in 2024-01, with the labels that each got.

#1123 Pythons/oncehub 73711 revert
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/core/selection/pseudo-checkbox/pseudo-checkbox.scss
  ui/src/components/select/search/option-search.scss
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
  ui/src/components/select/select.scss
  ui/src/components/tabs/_tabs-common.scss
  ui/src/components/tabs/tab-header.html
  ui/src/components/tabs/tab-nav-bar/tab-nav-bar.html
Labels: approved, size/L

#1125 Update the package version to 8.0.3
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tabs/_tabs-common.scss
Labels: size/S, approved

#1127 fixed the spacing issue in oui-tab
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tabs/_tabs-common.scss
  ui/src/components/tabs/tab-group.scss
Labels: size/S, approved

#1128 Merging staging-app2 in to master.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/core/selection/pseudo-checkbox/pseudo-checkbox.scss
  ui/src/components/select/search/option-search.scss
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
  ui/src/components/select/select.scss
  ui/src/components/tabs/_tabs-common.scss
  ui/src/components/tabs/tab-group.scss
  ui/src/components/tabs/tab-header.html
  ui/src/components/tabs/tab-nav-bar/tab-nav-bar.html
Labels: size/XXL, approved

#1129 Fixed the spacing and added padding in label in oui-tabs
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/tabs/_tabs-common.scss
Labels: size/S, approved
