Repository scheduleonce/once-ui, pull requests merged in 2024-05, with the labels that each got.

#1179 Upgraded package gulp.
  package-lock.json
  package.json
Labels: size/XXL, approved

#1181 added toggleFocus in dialog ref
  ui/src/components/dialog/dialog-ref.ts
  ui/src/components/dialog/dialog.ts
Labels: size/S, approved

#1182 upgraded version to 8.0.15-beta-04
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved

#1183 Merging staging-app2 in to master.
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile
  package-lock.json
  package.json
Labels: approved, size/L

#1184 fix issue for adding focus
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/dialog/dialog-container.ts
Labels: size/S, approved

#1186 Fix: ONCEHUB-74911 Make the cancel and done buttons(actionItems) customizable as per the requirement.
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
  ui/src/stories/select/select.stories.mdx
Labels: approved, size/M

#1187 Fix: ONCEHUB-79555 [once-ui] Make the cancel and done buttons(actionItems) customizable as per the requirement.
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
  ui/src/components/select/select.html
  ui/src/stories/select/select.stories.mdx
Labels: approved, size/M

#1188 Feat: ONCEHUB-82219 [once-ui] Disable the "Done" button (action items) according to the user's preferences.
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
  ui/src/stories/select/select.stories.mdx
Labels: approved, size/M

#1189 Feat: ONCEHUB-82219 [once-ui] Disable the "Done" button (action items) according to the user's preferences
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
  ui/src/stories/select/select.stories.mdx
Labels: approved, size/M

#1190 Merging staging-app2 in to master.
  package-lock.json
  package.json
Labels: size/XXL, approved

#1191 Text links have rounded corner focus states in Safari browser
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/button/button.ts
Labels: size/S, approved
