Repository scheduleonce/once-ui, pull requests merged in 2025-07, with the labels that each got.

#1368 FIX: Slight blink is observed when clicking any drop down menu option of three dots or where Double Popup overlays exist.
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/dialog/dialog.ts
Labels: approved, size/M

#1371 Mavericks/oncehub 96045
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/dialog/dialog.ts
Labels: size/S, approved

#1375 Merging staging-app2 in to master.
  .lighthouse/jenkins-x/pullrequest.yaml
  CHANGELOG.md
  Dockerfile
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: approved

#1376 FIX: Slight blink is observed when clicking any drop down menu option of three dots or where Double Popup overlays exist.
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/dialog/dialog.ts
Labels: size/S, approved
