Repository scheduleonce/once-ui, pull requests merged in 2025-06, with the labels that each got.

#1360 FIX: CVE-2025-5889 vulnerability found in package brace-expansion in project once-ui
  package-lock.json
Labels: approved, size/M

#1361 Merging staging-app2 in to master.
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/L

#1363 remove unsued package
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/autocomplete/autocomplete.html
Labels: approved, size/L

#1366 update base image in Dockerfile to node:22.16.0-alpine3.22
  Dockerfile
Labels: size/XS, approved
