Repository scheduleonce/once-ui, pull requests merged in 2025-02, with the labels that each got.

#1299 Update npm packages
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile
Labels: approved

#1300 Merging staging-app2 in to master.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/XXL, approved

#1302 Update npm packages
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile
Labels: size/XS, approved

#1303 [Team]ONCEHUB-91168: added cross icon in the search bar for the dropdown and fixed issue where removing search text still the value getting saved after discarding the changes
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/search/index.ts
  ui/src/components/select/search/option-search.html
  ui/src/components/select/search/option-search.scss
  ui/src/components/select/select.component.ts
Labels: approved, size/M

#1304 [Team] ONCEHUB-91168:Updated the value which was private to public so that i can get the value in html
  ui/src/components/select/search/index.ts
Labels: size/XS, approved

#1305 [QA]ONCEHUB-91168: Filter field inside Drop down menu - shared component
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/search/index.ts
  ui/src/components/select/search/option-search.html
  ui/src/components/select/search/option-search.scss
  ui/src/components/select/select.component.ts
Labels: approved, size/M

#1309 FIX: [ONCE-UI] Done gets enable while there were no changes in the dropdown
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
Labels: approved, size/M

#1310 Mavericks/oncehub 79151 qa
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
Labels: approved, size/M

#1311 Merging staging-app2 in to master.
  .lighthouse/jenkins-x/pullrequest.yaml
  CHANGELOG.md
  Dockerfile
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/search/index.ts
  ui/src/components/select/search/option-search.html
  ui/src/components/select/search/option-search.scss
  ui/src/components/select/select.component.ts
Labels: approved, size/M

#1312 Fix: the issue of disable button when there is no selection
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
Labels: size/S, approved

#1313 Mavericks/oncehub 79151 qa
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
Labels: size/S, approved

#1314 Mavericks/oncehub 79151 2 team
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
Labels: size/S, approved

#1315 Revert the code for number type input
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/form-field/_form-field-theme.scss
  ui/src/components/input/input-module.ts
  ui/src/components/input/input.ts
Labels: approved, size/L
