Repository scheduleonce/once-ui, pull requests merged in 2025-03, with the labels that each got.

#1318 FIX: [ONCE-UI] Done gets enable while there were no changes in the dropdown - ONCEHUB-79151
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
Labels: approved, size/M

#1322 updated version 8.0.38-beta.0 in package.json
  ui/package-lock.json
  ui/package.json
Labels: size/XS, approved

#1323 Merging staging-app2 in to master.
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/select.component.ts
Labels: approved, size/M

#1321 Update npm packages
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile
Labels: size/S

#1324 Update staging-app2 branch in trigger.yaml
  .lighthouse/jenkins-x/triggers.yaml
Labels: size/XS

#1325 Adding accessibility for screenreader in Table component
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/table/cell.ts
  ui/src/components/table/table.scss
Labels: size/S, approved

#1326 Adding accessibility for screenreader in Table component
  CHANGELOG.md
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/table/cell.ts
  ui/src/components/table/table.scss
Labels: size/S, approved
