Repository scheduleonce/once-ui, pull requests merged in 2025-04, with the labels that each got.

#1334 fix : ONCEHUB-96201 - UI disruption issue for action buttons inside oui-dialog.
  .storybook/preview-head.html
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/core/cdk/overlay/_overlay.scss
  ui/src/components/dialog/dialog.scss
Labels: size/S, approved

#1335 Merging staging-app2 in to master.
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/triggers.yaml
  CHANGELOG.md
  Dockerfile
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/table/cell.ts
  ui/src/components/table/table.scss
Labels: approved, size/M

#1339 Fix: ONCEHUB-96594 Filter not working with space on user notification page
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/filter.pipe.ts
Labels: size/XXL, approved

#1340 Fix: Enhance deployment script to handle existing package scenario
  .lighthouse/jenkins-x/release.yaml
Labels: size/XS, approved

#1341 fix: ONCEHUB-96594 Update filterOptions pipe to accept an array of fields instead of a single string.
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/filter.pipe.ts
Labels: size/XXL, approved

#1342 [TEAM] ONCEHUB-96594 fix filtering issue
  package-lock.json
  package.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/select/filter.pipe.ts
Labels: size/S, approved
